Areas/FieldDetermination/Controllers/WorkplaceEnvAndFugutiveFieldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LIMS_DEMO.Areas.FieldDetermination.Models;
using LIMS_DEMO.Areas.Arrival.Models;
using LIMS_DEMO.Core;
using LIMS_DEMO.Core.FieldDetermination;
using LIMS_DEMO.BAL;
using LIMS_DEMO.BAL.FieldDetermination;
using LIMS_DEMO.BAL.Arrival;
using LIMS_DEMO.BAL.DropDown;

namespace LIMS_DEMO.Areas.FieldDetermination.Controllers
{
    [RouteArea("FieldDetermination")]
    public class WorkplaceEnvAndFugutiveFieldController : Controller
    {
        string strStatus = "";
        public WorkplaceEnvAndFugutiveFieldController()
        {
            BALFactory.workplaceAndFugitiveEmissionBAL = new WorkplaceAndFugitiveEmissionBAL();
            BALFactory.enquiryBAL = new BAL.Enquiry.EnquiryBAL();
            BALFactory.samplecollectionBAL = new BAL.Collection.SampleCollectionBAL();
            BALFactory.samplearrivalBAL = new SampleArrivalBAL();
            BALFactory.dropdownsBAL = new DropDownBal();
        }

        // GET: FieldDetermination/WorkplaceEnvAndFugutiveField

        [HttpGet]
        public ActionResult WorkplaceEnvAndFugitiveEmissionField(int? SampleCollectionId = 0, int? EnquiryId = 0, int? EnquirySampleID = 0, int? FieldId = 0)
        {
            FDWorkplaceEnvAndFugutiveEmissionModel model = new FDWorkplaceEnvAndFugutiveEmissionModel();
            model.GridModel = new List<FDWorkplaceEnvAndFugutiveEmissionModel>();
            model.SampleCollectionId = SampleCollectionId;
            model.EnquiryId = EnquiryId;
            model.EnquirySampleID = (long)EnquirySampleID;
            TempData.Remove("WorkplaceList");

            if (FieldId != 0)
            {
                FDWorkplaceInfo workplaceInfo = BALFactory.workplaceAndFugitiveEmissionBAL.GetWorkPlaceDetails((Int32)FieldId, (Int32)SampleCollectionId);
                if (workplaceInfo != null)
                {
                    //CoreFactory.workplaceAndFugitiveEmissionEntity = BALFactory.workplaceAndFugitiveEmissionBAL.GetWorkPlaceDetails((Int32)WorkplaceID);
                    model.WorkplaceID = (Int32)FieldId;
                    model.SampleCollectionId = SampleCollectionId;
                    model.EnquiryId = EnquiryId;
                    model.StatusId = workplaceInfo.WorkplaceDetails.StatusId;
                    model.CurrentStatus = workplaceInfo.WorkplaceDetails.CurrentStatus;
                    ViewBag.CurrentStatus = workplaceInfo.WorkplaceDetails.CurrentStatus;
                    model.SurveyDate = Convert.ToDateTime(workplaceInfo.WorkplaceDetails.SurveyDate).Date;
                    model.SurveyDateDisplay = Convert.ToDateTime(model.SurveyDate).ToString("dd/MM/yyyy");
                    model.InstrumentId = workplaceInfo.WorkplaceDetails.InstrumentId;
                    model.DurationOfSampling = (Int32)workplaceInfo.WorkplaceDetails.DurationOfSampling;
                    model.FilterPaperAnalyzed = workplaceInfo.WorkplaceDetails.FilterPaperAnalyzed;
                    model.FilterPaperNo = (Int32)workplaceInfo.WorkplaceDetails.FilterPaperNo;
                    model.FlowRate_Final = (Int32)workplaceInfo.WorkplaceDetails.FlowRate_Final;
                    model.FlowRate_Initial = (Int32)workplaceInfo.WorkplaceDetails.FlowRate_Initial;
                    model.FlowRate_Avg = (Int32)workplaceInfo.WorkplaceDetails.FlowRate_Avg;
                    //model.RelativeHumidity = CoreFactory.workplaceAndFugitiveEmissionEntity.RelativeHumidity;
                    model.RelativeHumidity = workplaceInfo.WorkplaceDetails.RelativeHumidity;
                    model.Temperature = workplaceInfo.WorkplaceDetails.Temperature;
                    model.AnyObservation = workplaceInfo.WorkplaceDetails.AnyObservation;

                    model.FilterPaperNo2 = workplaceInfo.WorkplaceDetails.FilterPaperNo2;
                    model.StartTime = workplaceInfo.WorkplaceDetails.StartTime;
                    model.EndTime = workplaceInfo.WorkplaceDetails.EndTime;
                    model.Sampling_Duration = workplaceInfo.WorkplaceDetails.Sampling_Duration;
                    model.AvgFlowRate = workplaceInfo.WorkplaceDetails.AvgFlowRate;
                    model.TotalVolAirPassed_L = workplaceInfo.WorkplaceDetails.TotalVolAirPassed_L;
                    model.TotalVolumeAirPassed_m3 = workplaceInfo.WorkplaceDetails.TotalVolumeAirPassed_m3;

                    int i = 1;
                    foreach (var grid1 in workplaceInfo.WorkplaceInfos)
                    {
                        try
                        {
                            model.GridModel.Add(new FDWorkplaceEnvAndFugutiveEmissionModel()
                            {
                                SrNo = i,
                                WorkplaceID = grid1.WorkplaceID,
                                WorkplaceGasID = grid1.WorkplaceGasID,
                                //GasesSampled = grid1.GasesSampled,
                                ParameterName = grid1.Parameters,
                                TestMethodName = grid1.TestMethodName,
                                InField = grid1.InField,
                                IsNABLAccredited = grid1.IsNABLAccredited,
                                RotameterFlow = grid1.RotameterFlow,
                                VolImpingingSol = grid1.VolImpingingSol,
                                BottleNo = grid1.BottleNo,
                                Duration = grid1.Duration,
                                Vs = grid1.Vs,
                                PreservationDone = grid1.PreservationDone,
                            });
                            i++;
                        }
                        catch (Exception ex)
                        {
                        }
                    }
                    TempData["WorkplaceList"] = model.GridModel;
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddWorkplaceEnvAndFugitiveEmissionField(FDWorkplaceEnvAndFugutiveEmissionModel model, string Save)
        {
            CoreFactory.workplaceAndFugitiveEmissionEntity = new WorkplaceAndFugitiveEmissionEntity();
            var workplaceList = (List<FDWorkplaceEnvAndFugutiveEmissionModel>)TempData.Peek("WorkplaceList");
            if (workplaceList != null)
            {
                if (workplaceList.Count > 0)
                {
                    foreach (var workplace in workplaceList)
                    {
                        //if (model.WorkplaceID == 0)
                        //{
                        CoreFactory.workplaceAndFugitiveEmissionEntity.WorkplaceID = Convert.ToByte(model.WorkplaceID);
                        CoreFactory.workplaceAndFugitiveEmissionEntity.SampleCollectionId = (long)model.SampleCollectionId;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.EnquiryId = model.EnquiryId;
                        //CoreFactory.workplaceAndFugitiveEmissionEntity.StatusId = (byte)iStatusId;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.SurveyDate = model.SurveyDate;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.InstrumentId = model.InstrumentId;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.DurationOfSampling = model.DurationOfSampling;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FilterPaperAnalyzed = model.FilterPaperAnalyzed;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FilterPaperNo = model.FilterPaperNo;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FlowRate_Final = model.FlowRate_Final;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FlowRate_Initial = model.FlowRate_Initial;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FlowRate_Avg = model.FlowRate_Avg;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.RelativeHumidity = model.RelativeHumidity;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.Temperature = model.Temperature;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.AnyObservation = model.AnyObservation;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FilterPaperNo2 = model.FilterPaperNo2;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.MatterSizeStartTime = model.MatterSizeStartTime;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.MatterSizeEndTime = model.MatterSizeEndTime;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.SamplingDurationDiff = model.SamplingDurationDiff;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.SamplingDurationFinal = model.SamplingDurationFinal;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.SamplingDurationInitial = model.SamplingDurationInitial;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FlowRateDiffM = model.FlowRateDiffM;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FlowRateInitialM = model.FlowRateInitialM;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.FlowRateFinalM = model.FlowRateFinalM;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.CycloneCupNo = model.CycloneCupNo;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.TimeTotalizerDiff = model.TimeTotalizerDiff;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.TimeTotalizerFinal = model.TimeTotalizerFinal;
                        CoreFactory.workplaceAndFugitiveEmissionEntity.TimeTotalizerInitial = model.TimeTotalizerInitial;


                        CoreFactory.workplaceAndFugitiveEmissionEntity.FilterPaperNo2 = model.FilterPaperNo2;

Areas/FieldDetermination/Views/WorkplaceEnvAndFugutiveField/WorkplaceEnvAndFugitiveEmissionField.cshtml
@model LIMS_DEMO.Areas.FieldDetermination.Models.FDWorkplaceEnvAndFugutiveEmissionModel
@{
    ViewBag.Title = "WorkplaceEnvAndFugitiveEmissionField";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Field Determination</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Field Determination</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Field Determination</li>
                                <li class="breadcrumb-item active" aria-current="page">Add Workplace Air/Fugitive Emission/Workplace Air/Indoor Air Quality Values</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>

            <!-- Default Basic Forms Start -->
            <div class="pd-20 card-box mb-30">
                <div class="clearfix">
                    <div class="pull-left">
                        <h4 class="text-blue h4">Add Workplace Air/Fugitive Emission/Workplace Air/Indoor Air Quality Values</h4>
                        <p class="mb-30">@*All bootstrap element classies*@</p>
                    </div>
                </div>
                @Html.HiddenFor(model => model.EnquirySampleID)
                <div Id="divParameterList">
                    @{
                        Html.RenderAction("_FieldParameterUnit", "FieldWasteWater", Model.EnquirySampleID);
                    }
                </div>

                @if (ViewBag.CurrentStatus != "SampleColl")
                {
                    <div id="divAddWorkplace">
                        @{ Html.RenderAction("_FieldWorkplaceEnvAndFugitiveEmissionList", "WorkplaceEnvAndFugutiveField"); }
                    </div>
                }

                @using (Ajax.BeginForm("AddWorkplaceEnvAndFugitiveEmissionField", "WorkplaceEnvAndFugutiveField", new { area = "FieldDetermination" }, new AjaxOptions() { HttpMethod = "Post", OnBegin = "VlidateClick()", OnSuccess = "WorkplaceSuccess" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.EnquiryId)
                    @Html.HiddenFor(model => model.SampleCollectionId)
                    @Html.HiddenFor(model => model.WorkplaceID)
                    <hr />
                    <div class="row">
                        <div class="card-box table-responsive">
                            <p class="text-muted font-13 m-b-30">
                            </p>
                            <div id="divGrid">
                                @{ Html.RenderAction("_FieldWorkplaceEnvAndFugitiveEmissionGrid", "WorkplaceEnvAndFugutiveField", Model);}
                            </div>
                            <br />
                            <div>
                                @{ Html.RenderAction("_FieldWorkplaceEnvAndFugitiveEmission", "WorkplaceEnvAndFugutiveField", Model);}
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row align-items-end item form-group">
                        <div class="col-md-12 col-sm-12">
                            @if (ViewBag.CurrentStatus == "SampleColl")
                            {
                                @*<button type="submit" id="btnSave" class="btn btn-round btn-secondary" name="Save" value="FieldSave" style="background-color:darkgrey" disabled="disabled">Save </button>*@
                                <button type="submit" id="btnSubmit" class="btn btn-round btn-secondary" name="Save" value="FieldSubmit" style="background-color:darkgrey" disabled="disabled">Submit</button>
                            }
                            else
                            {
                                @*<button type="submit" id="btnSave" class="btn btn-success" name="Save" value="FieldSave">Save </button>*@
                                <button type="submit" id="btnSubmit" class="btn btn-primary" name="Save" value="FieldSubmit">Submit</button>
                            }
                        </div>
                    </div>
                }

                <!-- Default Basic Forms End -->
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>


<script>

    function VlidateClick() {
        debugger
        $('#btnSubmit').val('Please Wait..');
        $('#btnSubmit').prop('disabled', true);
    }

    function WorkplaceSuccess(result) {
        if (result.WorkPlaceID != "0") {
            alert('Values Entered successfully.');
            window.location.href = '/Collection/SampleCollection/CollectorList?CollectedBy=' + 1;
        }
    }
</script>

Areas/FieldDetermination/Views/WorkplaceEnvAndFugutiveField/_FieldWorkplaceEnvAndFugitiveEmissionGrid.cshtml
@model LIMS_DEMO.Areas.FieldDetermination.Models.FDWorkplaceEnvAndFugutiveEmissionModel

<div class="card-box mb-30">
    <div class="pb-20">

        @if (Model.GridModel.Count() > 0)
        {
            <table id="tblField" class="data-table table stripe hover nowrap">
                <thead>
                    <tr class="thead-dark">
                        <th class="table-plus datatable-nosort">
                            SrNo.
                        </th>
                        <th class="table-plus datatable-nosort">
                            Parameters
                        </th>
                        <th class="table-plus datatable-nosort">
                            TestMethod
                        </th>
                        <th class="table-plus datatable-nosort">
                            Vol Impinging Sol
                        </th>
                        <th class="table-plus datatable-nosort">
                            BottleNo
                        </th>
                        <th class="table-plus datatable-nosort">
                            RotameterFlow
                        </th>
                        <th class="table-plus datatable-nosort">
                            Duration
                        </th>
                        <th class="table-plus datatable-nosort">
                            Vs
                        </th>
                        <th class="table-plus datatable-nosort">
                            PreservationDone
                        </th>
                        @if (Model.CurrentStatus != "SampleColl")
                        {
                            <th class="table-plus datatable-nosort">
                                Action
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.GridModel.Count; i++)
                    {
                        <tr>
                            <td>
                                @Model.GridModel[i].SrNo
                            </td>
                            <td>
                                @Model.GridModel[i].ParameterName
                            </td>
                            <td>
                                @Model.GridModel[i].TestMethodName
                            </td>
                            <td>
                                @Model.GridModel[i].VolImpingingSol
                            </td>
                            <td>
                                @Model.GridModel[i].BottleNo
                            </td>
                            <td>
                                @Model.GridModel[i].RotameterFlow
                            </td>
                            <td>
                                @Model.GridModel[i].Duration
                            </td>
                            <td>
                                @Model.GridModel[i].Vs
                            </td>
                            <td>
                                @Model.GridModel[i].PreservationDone
                            </td>
                            @if (Model.CurrentStatus != "SampleColl")
                            {
                                <td>
                                    @*<a href="#" onclick="funEditField(@Model.GridModel[i].SrNo);">Edit</a> |*@
                                    <a href="#" onclick="funDeleteField(@Model.GridModel[i].SrNo);">Delete</a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }

    </div>
</div>
<!-- Simple Datatable End -->

<script>

    function funEditField(Id) {
        debugger
        $("#tblField").attr("disabled", true);
        $('#divAddWorkplace').load('/FieldDetermination/WorkplaceEnvAndFugutiveField/_FieldWorkplaceEnvAndFugitiveEmissionList?Id=' + Id);
        //$('#divList').hide();
    }

    function funDeleteField(Id) {
        debugger
        if (confirm('Are you sure you want to delete this record?')) {
            $.ajax({
                url: '/FieldDetermination/WorkplaceEnvAndFugutiveField/_DeleteBuildingMaterialField?Id=' + Id,
                type: 'Get',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                dataType: 'json',
                success: function (result) {
                    if (result.status == "success") {
                        $('#divGrid').load('/FieldDetermination/WorkplaceEnvAndFugutiveField/_FieldWorkplaceEnvAndFugitiveEmissionGrid');
                    }
                },
                error: function (data) {
                }
            });
        }
    }
</script>

Areas/FieldDetermination/Views/WorkplaceEnvAndFugutiveField/_FieldWorkplaceEnvAndFugitiveEmissionList.cshtml
@model LIMS_DEMO.Areas.FieldDetermination.Models.FDWorkplaceEnvAndFugutiveEmissionModel

@using (Ajax.BeginForm("_FieldWorkplaceEnvAndFugitiveEmissionList", "WorkplaceEnvAndFugutiveField", new { area = "FieldDetermination" }, new AjaxOptions() { HttpMethod = "Post", OnSuccess = "FDAdd" }, new { id = "frmAddWorkplace" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SrNo)
    @Html.HiddenFor(model => model.WorkplaceID)
    @Html.HiddenFor(model => model.WorkplaceGasID)
    @Html.HiddenFor(model => model.EnquirySampleID)

    <div class="form-horizontal align align-content-lg-center">
        <div class="card shadow mb-4">
            <div class="card-body align-content-center">
                <table class="table table-bordered" id="tblGasesSampling" width="100%" cellspacing="0">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ParameterName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TestMethodName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.VolImpingingSol)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.BottleNo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.RotameterFlow)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Duration)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Vs)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PreservationDone)
                        </th>
                    </tr>
                    <tr>
                        <td>
                            @Html.DropDownListFor(model => model.ParameterMasterId, new SelectList(ViewBag.Parameter, "ParameterMasterId", "ParameterName"), "--- Select ---", new { @class = "form-control" })
                            @Html.HiddenFor(model => model.ParameterName)
                        </td>
                        <td>
                            @Html.DropDownListFor(model => model.TestMethodId, new SelectList(ViewBag.TestMethod, "TestMethodId", "TestMethodName"), "--- Select ---", new { @class = "form-control" })
                            @Html.HiddenFor(model => model.TestMethodName)
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.VolImpingingSol, new { @class = "form-control", @placeholder = "VolImpingingSolution" })
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.BottleNo, new { @class = "form-control", @placeholder = "BottleNo" })
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.RotameterFlow, new { @class = "form-control", @placeholder = "RotaMeterFlow" })
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.Duration, new { @class = "form-control", @placeholder = "Duration" })
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.Vs, new { @class = "form-control", @placeholder = "VS" })
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.PreservationDone, new { @class = "form-control", @placeholder = "Preservation Done" })
                        </td>
                    </tr>
                </table>
                <div class="row">
                    <div class="form-group col-md-12">
                        <div class="col-md-12 col-sm-12">
                            @{ string btnText = "Add";
                                if (Model.SrNo != 0)
                                {
                                    btnText = "Update";
                                    <input class="btn btn-primary btn-sm alignright" onclick="CancelNameValues();" id="btnCancel" value="Cancel" />
                                }
                            }
                            <input class="btn btn-success btn-sm alignright" onclick="SetNameValues();" type="submit" id="btnAdd" value="@btnText" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    $(function () {
        $("#frmAddWorkplace").removeData("validator");
        $("#frmAddWorkplace").removeData("unobtrusiveValidation");
       // $.validator.unobtrusive.parse("#frmAddWorkplace");
    })

    function FDAdd(result) {
        debugger
        $('#divGrid').load('/FieldDetermination/WorkplaceEnvAndFugutiveField/_FieldWorkplaceEnvAndFugitiveEmissionGrid');
        $('#divAddBuildingMaterial').load('/FieldDetermination/WorkplaceEnvAndFugutiveField/_FieldWorkplaceEnvAndFugitiveEmissionList');

    }

    function CancelNameValues() {
        $('#ParameterMasterId').val(-1);
        $('#TestMethodId').val(-1);
        $('#VolImpingingSol').val("");
        $('#BottleNo').val("");
        $('#RotameterFlow').val("");
        $('#Duration').val("");
        $('#btnAdd').val("Add")
        $('#btnCancel').css('display', 'none')
        $('#SrNo').val(0)
    }

    function SetNameValues() {
        debugger;
        $('#ParameterName').val($('#ParameterMasterId option:selected').text());
        $('#TestMethodName').val($('#TestMethodId option:selected').text());
    }

    $('#ParameterMasterId').change(function () {
        debugger
        if ($('#ParameterMasterId').val() == '') {
            $('#TestMethodId').html('');
            $('#TestMethodId').append('<option value="">---Select---</option>');
        }
        else {

            $('#TestMethodId').html('');
            $('#TestMethodId').append('<option value="">---Select---</option>');
            $.ajax({
                url: '/FieldDetermination/FieldWasteWater/GetTestMethod?EnquirySampleID=' + $('#EnquirySampleID').val() + "&ParameterMasterId=" + $('#ParameterMasterId').val(),
                type: 'Get',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                dataType: 'json',
                success: function (result) {
                    debugger
                    $.each(result.result, function (i, item) {
                        $('#TestMethodId').append('<option value="' + item.TestMethodId + '">' + item.TestMethodName + '</option>');
                    })

                    $('#TestMethodId').append('<option value="' + 0 + '">' + "Not Required" + '</option>');
                },
                error: function (data) {
                }
            });
        }
    });
</script>