Areas/Lab/Controllers/TesterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LIMS_DEMO.BAL;
using LIMS_DEMO.BAL.Lab;
using LIMS_DEMO.Core;
using LIMS_DEMO.Core.Lab;
using LIMS_DEMO.Common;
using Newtonsoft.Json;
using System.Drawing;
using System.Drawing.Imaging;
using ZXing;
using System.IO;
using LIMS_DEMO.Core.Configuration;



namespace LIMS_DEMO.Areas.Lab.Controllers
{
    public class TesterController : Controller
    {
        // GET: Lab/Tester
        public TesterController()
        {
            BALFactory.testerBAL = new TesterBAL();
            BALFactory.dropdownsBAL = new BAL.DropDown.DropDownBal();
        }
        public ActionResult SampleList()
        {
            var DisciplineId = CoreFactory.userEntity.DisciplineId;
            int UserMasterId = CoreFactory.userEntity.UserMasterID;

            IList<Core.Lab.TesterEntity> testerEntities = BALFactory.testerBAL.GetList(DisciplineId, UserMasterId);
            return View(testerEntities);
           
        }
        public ActionResult ParameterList(string SampleId)
        {
            int DisciplineId = CoreFactory.userEntity.DisciplineId;
            int UserMasterId = CoreFactory.userEntity.UserMasterID;

            SampleParameterInfo sampleParameterInfo = BALFactory.testerBAL.GetParameterInfo(Convert.ToInt32(SampleId), DisciplineId, UserMasterId);
            return View(sampleParameterInfo);

        }
        public ActionResult Tester(long ParameterMasterId, long SampleId)
        {
            int DisciplineId = CoreFactory.userEntity.DisciplineId;
            int UserMasterId = CoreFactory.userEntity.UserMasterID;
            SampleParameterAnalysis sampleParameterAnalysis = BALFactory.testerBAL.GetSampleParameterAnalysis(Convert.ToInt32(SampleId), DisciplineId, UserMasterId, ParameterMasterId);
            string QRCodeText = "SampleNumber:" + sampleParameterAnalysis.SampleNameOriginal + ",ParameterName:" + sampleParameterAnalysis.ParameterName + ",ParameterId:" + sampleParameterAnalysis.ParameterMasterId.ToString();

            string imgPath = "QRCode_" + SampleId + ParameterMasterId + ".jpg";
            sampleParameterAnalysis.QRCodePath = imgPath;
            GenerateCode(QRCodeText, imgPath);
            ViewBag.SampleCollectionId = SampleId;
            return View(sampleParameterAnalysis);
          
        }
        private void GenerateCode(string text, string FileName)
        {
            try
            {
                var writer = new BarcodeWriter();
                writer.Format = BarcodeFormat.QR_CODE;
                var result = writer.Write(text);
                string path = Server.MapPath("/Content/images/" + FileName);
                var barcodeBitmap = new Bitmap(result);
                using (MemoryStream memory = new MemoryStream())
                {
                    using (FileStream fs = new FileStream(path, FileMode.Create, FileAccess.ReadWrite))
                    {
                        barcodeBitmap.Save(memory, ImageFormat.Jpeg);
                        byte[] bytes = memory.ToArray();
                        fs.Write(bytes, 0, bytes.Length);
                    }
                }
            }
            catch (Exception ex)
            {
                
            }
        }

        public long SaveSolutionPreparationData(string model)
        {
            try
            {
                SolutionPreparationData solutionPreparationData = JsonConvert.DeserializeObject<SolutionPreparationData>(model);
                solutionPreparationData.EnteredBy = CoreFactory.userEntity.UserMasterID;

                long Id = BALFactory.testerBAL.SaveSolutionPreparationData(solutionPreparationData);
                return Id;
            }
            catch (Exception ex)
            {
                
                return 0;
            }

        }

        public JsonResult GetSolutionPreparationData(int ParameterMasterId, int SampleCollectionId, int ParameterGroupId)
        {
            try
            {
                SolutionPreparationData solutionPreparationData = new SolutionPreparationData();
                solutionPreparationData.ParameterMasterId = ParameterMasterId;
                solutionPreparationData.SampleCollectionId = SampleCollectionId;
                solutionPreparationData.ParameterGroupId = ParameterGroupId;

                IList<SolutionPreparationData> objSolutionPreparationData = BALFactory.testerBAL.GetSolutionPreparationData(solutionPreparationData);
                return Json(objSolutionPreparationData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                
                return null;
            }
        }
        public JsonResult GetChemicalUsedData(int ParameterMasterId, int SampleCollectionId, int ParameterGroupId, string nameOfSolution)
        {
            try
            {
                SolutionPreparationData solutionPreparationData = new SolutionPreparationData();
                solutionPreparationData.ParameterMasterId = ParameterMasterId;
                solutionPreparationData.SampleCollectionId = SampleCollectionId;
                solutionPreparationData.ParameterGroupId = ParameterGroupId;
                solutionPreparationData.NameOfSolution = nameOfSolution;
                IList<SolutionPreparationData> objSolutionPreparationData = BALFactory.testerBAL.GetChemicalUsedData(solutionPreparationData);
                return Json(objSolutionPreparationData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                
                return null;
            }
        }

        public JsonResult InsertAvgValue(int ParameterMasterId, int SampleCollectionId, int ParameterGroupId, string[] avgResult)
        {
            try
            {
                bool result = BALFactory.testerBAL.UpdateAvgValue(SampleCollectionId, ParameterMasterId, ParameterGroupId, avgResult);
                return Json("Calculated Values Updated.");
            }
            catch (Exception ex)
            {
                
                return null;
            }
        }
        public JsonResult GetFormula(int ParameterMasterId, int TestMethodId, int ParameterGroupId, int UnitId, int SampleCollectionId)
        {
            try
            {
                Core.Configuration.ParameterFormulaList objParam = new Core.Configuration.ParameterFormulaList();
                objParam.ParameterId = ParameterMasterId;
                objParam.TestMethodId = TestMethodId;
                objParam.ParameterGroupId = ParameterGroupId;
                objParam.UnitId = UnitId;
                objParam.SampleCollectionId = SampleCollectionId;
                Core.Configuration.ParameterFormulaList parameterFormulaList = BALFactory.testerBAL.GetFormula(objParam);

                return Json(parameterFormulaList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
               
                return null;
            }
        }

        public JsonResult GetFinalResRow(int ParameterMasterId, int TestMethodId, int ParameterGroupId, int UnitId, int SampleCollectionId)
        {
            try
            {
                Core.Configuration.ParameterFormulaList objParam = new Core.Configuration.ParameterFormulaList();
                objParam.ParameterId = ParameterMasterId;
                objParam.TestMethodId = TestMethodId;
                objParam.ParameterGroupId = ParameterGroupId;
                objParam.UnitId = UnitId;
                objParam.SampleCollectionId = SampleCollectionId;
                Core.Configuration.ParameterFormulaList finalResultRow = BALFactory.testerBAL.GetFinalResultRows(objParam);
                return Json(finalResultRow, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
               
                return null;
            }
        }

        public JsonResult UpdateCalculatedValue(string FormulaList, int SampleCollectionId, string TestingHours)
        {
            try
            {
                List<Core.Configuration.FormulaList> formulaList = JsonConvert.DeserializeObject<List<Core.Configuration.FormulaList>>(FormulaList);
                int UserMasterId = CoreFactory.userEntity.UserMasterID;
                bool result = BALFactory.testerBAL.UpdateCalculatedValue(formulaList, SampleCollectionId, UserMasterId, TestingHours);
                //bool result2 = BALFactory.analyseBAL.UpdateAvgValue(formulaList, SampleCollectionId, UserMasterId, TestingHours);
                return Json("Calculated Values Updated.");
            }
            catch (Exception ex)
            {
               
                return null;
            }
        }
        public JsonResult UpdateFinalResult(string model, bool isSubmitted)
        {
            try
            {
                AnalysisProcessScheduleDetail analysisProcessScheduleDetail = JsonConvert.DeserializeObject<AnalysisProcessScheduleDetail>(model);

                analysisProcessScheduleDetail.EnteredBy = CoreFactory.userEntity.UserMasterID;
                analysisProcessScheduleDetail.EnteredDate = DateTime.UtcNow;
                var status = BALFactory.testerBAL.UpdateFinalResult(analysisProcessScheduleDetail, isSubmitted);

                string Msg = "Sample Received for Approve";//samples received for review from tester

                long NotificationDetailId = BALFactory.testerBAL.AddNotification(Msg, "Planner", analysisProcessScheduleDetail);
                long NotificationDetailId1 = BALFactory.testerBAL.AddNotification(Msg, "Reviewer", analysisProcessScheduleDetail);

                return Json(status);
            }
            catch (Exception ex)
            {
               
                return null;
            }
        }

        public JsonResult GetTestProcessScheduler(string model)
        {

Areas/Lab/Views/Tester/ParameterList.cshtml
@model LIMS_DEMO.Core.Lab.SampleParameterInfo
@using LIMS_DEMO.Common
@{
    ViewBag.Title = "ParameterList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var recordCount = Model.ParameterInfos.Count();
    CurrentStatusEnum currentStatus;
}
@{ long SampleCollectionId = Model.SampleDetails.SampleCollectionId;}
<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">

            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Tester</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active" aria-current="page">Tester</li>
                                <li class="breadcrumb-item active" aria-current="page">Parameter List</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <!-- Default Basic Forms Start -->
            <div class="pd-20 card-box mb-30">
                <div class="clearfix">
                    <div class="pull-left">
                        <h4 class="text-blue h4">Parameter List</h4>
                        <p class="mb-30">@*All bootstrap element classies*@</p>
                    </div>
                    @*<div class="pull-right">
                          <a href="#basic-form1" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="collapse" role="button"><i class="fa fa-code"></i> Source Code</a>
                        </div>*@
                </div>
                <!-- Simple Datatable start -->
                <div class="card-box mb-30">
                    <div class="pb-20">
                        <table class="data-table table stripe hover nowrap">
                            <thead>
                                <tr class="thead-dark">
                                   
                                    <th class="table-plus datatable-nosort">Sample ID</th>
                                    <th>Sample Type</th>
                                    <th>
                                        Product Group Name
                                    </th>
                                    <th>
                                        Sub Group Name
                                    </th>
                                    <th>
                                        Matrix
                                    </th>
                                </tr>
                            </thead>
                            <tbody>

                                
                                        <tr>
                                            <td>@Model.SampleDetails.SampleNameOriginal</td>
                                            <td>@Model.SampleDetails.SampleTypeProductName</td>
                                            <td>@Model.SampleDetails.ProductGroupName</td>
                                            <td>@Model.SampleDetails.SubGroupName</td>
                                            <td>@Model.SampleDetails.MatrixName</td>
                                          </tr>
                            </tbody>

                            <tfoot>
                                <tr>
                                    <td colspan="9">

                                        <div class="dataTables_paginate paging_simple_numbers" id=""></div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

                <hr/>
                <div class="card-box mb-30">
                    <div class="pb-20">
                        <table class="data-table table stripe hover nowrap">
                            <thead>
                                <tr class="thead-dark">
                                    <th class="table-plus datatable-nosort">Sr No.</th>
                                    <th>Parameter</th>
                                    <th>Test Method</th>
                                    <th>Unit</th>
                                    <th>
                                        Remark
                                    </th>
                                    <th>
                                        Current Status
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int rowNo = 0; }
                                @foreach (var item in Model.ParameterInfos)
                                {
                                    currentStatus = (CurrentStatusEnum)Enum.ToObject(typeof(CurrentStatusEnum), item.CurrentStatus);
                                    <tr>
                                        <td>
                                            @{ rowNo++; }
                                            @rowNo
                                        </td>
                                        @if (item.CurrentStatus == 1 || item.CurrentStatus == 4)
                                        {
                                            <td>
                                                @Html.ActionLink(item.ParameterName, "Tester", "Tester", new { @ParameterMasterId = item.ParameterMasterId, @SampleId = SampleCollectionId }, null)
                                            </td>
                                        }
                                        else
                                        {
                                            <td>
                                               @item.ParameterName
                                            </td>
                                        }
                                        <td>
                                           @item.Unit
                                        </td>
                                        <td>
                                           @item.TestMethod
                                        </td>
                                        <td>
                                           @item.ReviewerComment
                                        </td>
                                        <td>
                                            @currentStatus
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="9">
                                        <div class="dataTables_paginate paging_simple_numbers" id=""></div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

            </div>
            <!-- Default Basic Forms End -->
        </div>
    </div>
</div>

Areas/Lab/Views/Tester/SampleList.cshtml
@model IEnumerable<LIMS_DEMO.Core.Lab.TesterEntity>
@{
    ViewBag.Title = "SampleList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">

            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Tester</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active" aria-current="page">Tester</li>
                                <li class="breadcrumb-item active" aria-current="page">Tester List</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <!-- Default Basic Forms Start -->
            <div class="pd-20 card-box mb-30">
                <div class="clearfix">
                    <div class="pull-left">
                        <h4 class="text-blue h4">Sample List</h4>
                    </div>
                    @*<div class="pull-right">
                          <a href="#basic-form1" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="collapse" role="button"><i class="fa fa-code"></i> Source Code</a>
                        </div>*@
                </div>
                <!-- Simple Datatable start -->
               
                    <div class="pb-20">
                        <table id="dtHorizontalExample" class="table table stripe hover nowrap">
                            <thead>
                                <tr class="thead-dark">
                                    <th class="table-plus datatable-nosort">Sr No.</th>
                                    <th>Sample ID</th>
                                    <th>Sample Type</th>
                                    <th>Product Group</th>
                                    <th>Sub Group</th>
                                    <th>Matrix</th>
                                    <th>Status Name</th>
                                    <th>Report</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int rowNo = 0; }
                                @if (Model.Count() > 0)
                                {
                                    foreach (var item in Model)
                                    {
                                <tr>
                                    <td class="table-plus">@{rowNo++;}@rowNo</td>
                                    <td>
                                        @*<a href="#"  style="color:blue">@item.SampleName</a>*@
                                        @Html.HiddenFor(modelitem => item.SampleCollectionId)
                                        @Html.ActionLink(item.SampleName, "ParameterList", "Tester", new { @SampleId = item.SampleCollectionId, style = "color:blue" }, null)
                                    </td>
                                    <td>@item.SampleTypeProductName</td>
                                    <td>@item.ProductGroupName</td>
                                    <td>@item.SubGroupName</td>
                                    <td>@item.MatrixName</td>
                                    <td>@item.StatusName</td>
                                    <td>
                                        <a href="../../Reporting/frmShowReport.aspx?path=TesterReport.rdl&SampleCollectionId=@item.SampleCollectionId" target="_blank">Download</a>
                                    </td>
                                    @if (item.AnalysisActive > 0)
                                    {
                                <td>
                                    <img src='/Content/images/active.png' alt='Active' id='imgStatus'>
                                </td> }
                                                    else
                                                    {
                                <td>
                                    <img src='/Content/images/unactive.png' alt='Inactive' id='imgStatus'>
                                </td>}
                                </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- Simple Datatable End -->
            </div>
            <!-- Default Basic Forms End -->
        </div>
    </div>
<script>
    $(document).ready(function () {
        $('#dtHorizontalExample').DataTable({
            "scrollX": true
        });
        $('.dataTables_length').addClass('bs-select');
    });
</script>