Areas/FieldDetermination/Controllers/FieldNoiseLevelMonitoringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LIMS_DEMO.Areas.FieldDetermination.Models;
using LIMS_DEMO.BAL;
using LIMS_DEMO.BAL.FieldDetermination;
using LIMS_DEMO.Core;
using LIMS_DEMO.Core.FieldDetermination;
namespace LIMS_DEMO.Areas.FieldDetermination.Controllers
{
    [RouteArea("FieldDetermination")]
    public class FieldNoiseLevelMonitoringController : Controller
    {
        string strStatus = "";
        public FieldNoiseLevelMonitoringController()
        {
            BALFactory.noiseLevelMonitoringBAL = new NoiseLevelMonitoringBAL();
            BALFactory.enquiryBAL = new BAL.Enquiry.EnquiryBAL();
            BALFactory.samplecollectionBAL = new BAL.Collection.SampleCollectionBAL();
        }

        // GET: FieldDetermination/FieldNoiseLevelMonitoring
        public ActionResult FieldNoiseLevelMonitoring(bool flag, int? SampleCollectionId = 0, int? EnquiryId = 0, int? EnquirySampleID = 0, int? FieldId = 0)
        {
            FDNoiseLevelMonitoringModel model = new FDNoiseLevelMonitoringModel();
            model.GridModel = new List<FDNoiseLevelMonitoringModel>();
            model.GridSourceModel = new List<FDNoiseLevelMonitoringModel>();
            model.SampleCollectionId = SampleCollectionId;
            model.EnquiryId = EnquiryId;
            model.EnquirySampleID = (long)EnquirySampleID;
            if (flag == true)
            {
                //For "Ambient Noise Level" & "Workplace Noise Level
                model.flag = true;
            }
            if (flag == false)
            {
                //For "Source Noise Level"
                model.flag = false;
            }

            TempData.Remove("NoiseLevelList");
            TempData.Remove("SourceNoiseLevelList");
            if (FieldId != 0)
            {
                NoiseLevelMonitoringEntity.FDNoiseInfo noiseInfo = BALFactory.noiseLevelMonitoringBAL.GetNoiseLevelDetails((Int32)FieldId, (Int32)SampleCollectionId);
                if (noiseInfo != null)
                {
                    model.FieldNoiseId = (Int32)FieldId;
                    model.SampleCollectionId = SampleCollectionId;
                    model.EnquiryId = EnquiryId;
                    model.StatusId = noiseInfo.NoiseDetails.StatusId;
                    model.CurrentStatus = noiseInfo.NoiseDetails.CurrentStatus;
                    ViewBag.CurrentStatus = noiseInfo.NoiseDetails.CurrentStatus;
                    model.Location = noiseInfo.NoiseDetails.Location;
                    model.LocationHeight = noiseInfo.NoiseDetails.LocationHeight;
                    model.LocationZone = noiseInfo.NoiseDetails.LocationZone;
                    model.LeqAvgDayTime = noiseInfo.NoiseDetails.LeqAvgDayTime;
                    model.LeqAvgNightTime = noiseInfo.NoiseDetails.LeqAvgNightTime;
                    model.L10AvgDayTime = noiseInfo.NoiseDetails.L10AvgDayTime;
                    model.L10AvgNightTime = noiseInfo.NoiseDetails.L10AvgNightTime;
                    model.L50AvgDayTime = noiseInfo.NoiseDetails.L50AvgDayTime;
                    model.L50AvgNightTime = noiseInfo.NoiseDetails.L50AvgNightTime;
                    model.L90AvgDayTime = noiseInfo.NoiseDetails.L90AvgDayTime;
                    model.L90AvgNightTime = noiseInfo.NoiseDetails.L90AvgNightTime;
                    model.LminAvgDayTime = noiseInfo.NoiseDetails.LminAvgDayTime;
                    model.LminAvgNightTime = noiseInfo.NoiseDetails.LminAvgNightTime;
                    model.LmaxAvgDayTime = noiseInfo.NoiseDetails.LmaxAvgDayTime;
                    model.LmaxAvgNightTime = noiseInfo.NoiseDetails.LmaxAvgNightTime;
                    model.InstrumentID = noiseInfo.NoiseDetails.InstrumentID;
                    model.InstrumentMake = noiseInfo.NoiseDetails.InstrumentMake;
                    model.InstrumentModel = noiseInfo.NoiseDetails.InstrumentModel;
                    model.MicrophoneHeight = noiseInfo.NoiseDetails.MicrophoneHeight;
                    model.Obstacles = noiseInfo.NoiseDetails.Obstacles;
                    model.WindType = noiseInfo.NoiseDetails.WindType;
                    model.Isolation = noiseInfo.NoiseDetails.Isolation;
                    model.Weather = noiseInfo.NoiseDetails.Weather;
                    model.MonitoringDate = noiseInfo.NoiseDetails.MonitoringDate;
                    model.MonitoringTime = noiseInfo.NoiseDetails.MonitoringTime;
                    model.DistancefrmSource = noiseInfo.NoiseDetails.DistancefrmSource;
                    model.ProminentNoiseSource = noiseInfo.NoiseDetails.ProminentNoiseSource;
                    model.BackgroundNoiselevel = noiseInfo.NoiseDetails.BackgroundNoiselevel;
                    int i = 1;
                    foreach (var grid1 in noiseInfo.NoiseInfos)
                    {
                        try
                        {
                            model.GridModel.Add(new FDNoiseLevelMonitoringModel()
                            {
                                SrNo = i,
                                FieldNoiseId = grid1.FieldNoiseId,
                                ParameterId = grid1.ParameterId,
                                TimeDuration = grid1.TimeDuration,
                                FileName = grid1.FileName,
                                LocationGrid = grid1.LocationGrid,
                                DayNight = grid1.DayNight,
                                ShiftName = grid1.ShiftName,
                                LeqFastResponse = grid1.LeqFastResponse,
                                LeqSlowResponse = grid1.LeqSlowResponse,
                                L10FastResponse = grid1.L10FastResponse,
                                L10SlowResponse = grid1.L10SlowResponse,
                                L50FastResponse = grid1.L50FastResponse,
                                L50SlowResponse = grid1.L50SlowResponse,
                                L90FastResponse = grid1.L90FastResponse,
                                L90SlowResponse = grid1.L90SlowResponse,
                                LminFastResponse = grid1.LminFastResponse,
                                LminSlowResponse = grid1.LminSlowResponse,
                                LmaxFastResponse = grid1.LmaxFastResponse,
                                LmaxSlowResponse = grid1.LmaxSlowResponse,
                                ParameterName = grid1.ParameterName,
                                TestMethodName = grid1.TestMethodName,
                                InField = grid1.InField,
                                IsNABLAccredited = grid1.IsNABLAccredited,
                            });

                            i++;
                        }
                        catch (Exception ex)
                        {

                        }
                    }

                    int j = 1;
                    foreach (var gridSource in noiseInfo.SourceNoiseInfos)
                    {
                        try
                        {
                            model.GridSourceModel.Add(new FDNoiseLevelMonitoringModel()
                            {
                                SrNo = j,
                                FieldNoiseId = gridSource.FieldNoiseId,
                                NoiseSourceParameterId = gridSource.NoiseSourceParameterId,
                                TimeSource = gridSource.TimeSource,
                                LocationGrid = gridSource.LocationGrid,
                                DayNight = gridSource.DayNight,
                                ShiftName = gridSource.ShiftName,
                                Inside = gridSource.Inside,
                                Outside = gridSource.Outside,
                                InsertionLoss = gridSource.InsertionLoss,
                                ParameterName = gridSource.ParameterName,
                                TestMethodName = gridSource.TestMethodName,
                                UnitName = gridSource.UnitName,
                                InField = gridSource.InField,
                                IsNABLAccredited = gridSource.IsNABLAccredited,
                            });
                            j++;
                        }
                        catch (Exception ex)
                        {
                        }
                    }
                    TempData["NoiseLevelList"] = model.GridModel;
                    TempData["SourceNoiseLevelList"] = model.GridSourceModel;
                }
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult FieldNoiseLevelMonitoring(FDNoiseLevelMonitoringModel model, string Save)
        {

            CoreFactory.noiseLevelMonitoringEntity = new NoiseLevelMonitoringEntity();
            var noiseLevelList = (List<FDNoiseLevelMonitoringModel>)TempData.Peek("NoiseLevelList");
            var sourcenoiseLevelList = (List<FDNoiseLevelMonitoringModel>)TempData.Peek("SourceNoiseLevelList");

            CoreFactory.noiseLevelMonitoringEntity.FieldNoiseId = Convert.ToByte(model.FieldNoiseId);
            CoreFactory.noiseLevelMonitoringEntity.SampleCollectionId = model.SampleCollectionId;
            CoreFactory.noiseLevelMonitoringEntity.EnquiryId = model.EnquiryId;
            CoreFactory.noiseLevelMonitoringEntity.MonitoringDate = model.MonitoringDate;
            CoreFactory.noiseLevelMonitoringEntity.MonitoringTime = model.MonitoringTime;
            CoreFactory.noiseLevelMonitoringEntity.Location = model.Location;
            CoreFactory.noiseLevelMonitoringEntity.LeqAvgDayTime = model.LeqAvgDayTime;
            CoreFactory.noiseLevelMonitoringEntity.LeqAvgNightTime = model.LeqAvgNightTime;
            CoreFactory.noiseLevelMonitoringEntity.L10AvgDayTime = model.L10AvgDayTime;
            CoreFactory.noiseLevelMonitoringEntity.L10AvgNightTime = model.L10AvgNightTime;

Areas/FieldDetermination/Views/FieldNoiseLevelMonitoring/_FieldNoiseLevelMonitoringList.cshtml
@model LIMS_DEMO.Areas.FieldDetermination.Models.FDNoiseLevelMonitoringModel

@using (Ajax.BeginForm("_FieldNoiseLevelMonitoringList", "FieldNoiseLevelMonitoring", new { area = "FieldDetermination" }, new AjaxOptions() { HttpMethod = "Post", OnSuccess = "FDAdd" }, new { id = "frmAddNoiseLevel" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SrNo)
    @Html.HiddenFor(model => model.FieldNoiseId)
    @Html.HiddenFor(model => model.ParameterId)
  
     <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h4 class="m-0 font-weight-bold text-primary text-xl-center"> Enter Values for Ambient Noise Level / Workplace Noise Level :</h4>
                </div>
                <div class="card-body">
                    <div class="col-md-12">
                        <table class="table table-bordered" id="datatable" data-filter="#filter" data-filter-text-only="true" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    @*<th>
                                            Parameters
                                        </th>*@
                                    <th>
                                        Shift
                                    </th>
                                    <th>
                                        TestMethod
                                    </th>
                                    <th>
                                        Location
                                    </th>
                                    <th>
                                        Day/Night
                                    </th>
                                    <th>
                                        Time Duration
                                    </th>
                                    <th>
                                        File Name
                                    </th>
                                    <th>
                                        Leq Fast Response/Leq Slow Response
                                    </th>
                                    <th>
                                        L10 Fast Response/Leq Slow Response
                                    </th>
                                    <th>
                                        L50 Fast Response/Leq Slow Response
                                    </th>
                                    <th>
                                        L90 Fast Response/Leq Slow Response
                                    </th>
                                    <th>
                                        Lmin Fast Response/Leq Slow Response
                                    </th>
                                    <th>
                                        Lmax Fast Response/Leq Slow Response
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    @*<td>
                                            @Html.DropDownListFor(model => model.ParameterMasterId, new SelectList(ViewBag.Parameter, "ParameterMasterId", "ParameterName"), "--- Select ---", new { @class = "form-control" })
                                            @Html.HiddenFor(model => model.ParameterName)
                                        </td>*@
                                    <td>
                                        <select class="form-control" id="ShiftName" name="ShiftName">
                                            <option value="Select Shift" disabled>Select Shift</option>
                                            <option value="1 Hour">1 Hour</option>
                                            <option value="24 Hour">24 Hour</option>
                                            <option value="Spot Noise">Spot Noise</option>
                                        </select>
                                    </td>
                                    <td>
                                        @Html.DropDownListFor(model => model.TestMethodId, new SelectList(ViewBag.TestMethod, "TestMethodId", "TestMethodName"), "--- Select ---", new { @class = "form-control" })
                                        @Html.HiddenFor(model => model.TestMethodName)
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.LocationGrid, new { @class = "form-control ", @placeholder = "Location" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.DayNight, new { @class = "form-control ", @placeholder = "DayOrNight" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.TimeDuration, new { @class = "form-control ", @placeholder = "TimeDuration" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.FileName, new { @class = "form-control ", @placeholder = "FileName" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.LeqFastResponse, new { @class = "form-control ", @placeholder = "Leq FastResponse" }) &nbsp;
                                        @Html.TextBoxFor(model => model.LeqSlowResponse, new { @class = "form-control ", @placeholder = "Leq SlowResponse" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.L10FastResponse, new { @class = "form-control ", @placeholder = "L10 FastResponse" }) &nbsp;
                                        @Html.TextBoxFor(model => model.L10SlowResponse, new { @class = "form-control ", @placeholder = "L10 SlowResponse" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.L50FastResponse, new { @class = "form-control ", @placeholder = "L50 FastResponse" }) &nbsp;
                                        @Html.TextBoxFor(model => model.L50SlowResponse, new { @class = "form-control ", @placeholder = "L50 SlowResponse" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.L90FastResponse, new { @class = "form-control ", @placeholder = "L90 FastResponse" }) &nbsp;
                                        @Html.TextBoxFor(model => model.L90SlowResponse, new { @class = "form-control ", @placeholder = "L90 SlowResponse" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.LminFastResponse, new { @class = "form-control ", @placeholder = "Lmin FastResponse" }) &nbsp;
                                        @Html.TextBoxFor(model => model.LminSlowResponse, new { @class = "form-control ", @placeholder = "Lmin SlowResponse" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.LmaxFastResponse, new { @class = "form-control ", @placeholder = "Lmax FastResponse" }) &nbsp;
                                        @Html.TextBoxFor(model => model.LmaxSlowResponse, new { @class = "form-control ", @placeholder = "Lmax SlowResponse" })
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-12">
                        @{ string btnText = "Add";
                            if (Model.SrNo != 0)
                            {
                                btnText = "Update";
                                <input class="btn btn-primary btn-sm alignright" onclick="CancelNameValues();" id="btnCancel" value="Cancel" />
                            }
                        }
                        <input class="btn btn-success btn-sm alignright" onclick="SetNameValues();" type="submit" id="btnAdd" value="@btnText" />
                        @*<input class="btn btn-success" type="submit" id="btnAdd" value="@btnText" />*@
                    </div>
                </div>
            </div>
        </div>
   
}

<script>
    $(function () {
        $("#frmAddNoiseLevel").removeData("validator");
        $("#frmAddNoiseLevel").removeData("unobtrusiveValidation");
        $.validator.unobtrusive.parse("#frmAddNoiseLevel");
    })

    function FDAdd(result) {
        $('#divList').load('/FieldDetermination/FieldNoiseLevelMonitoring/_FDNoiseLevelGridList');
        $('#divAddNoiseLevel').load('/FieldDetermination/FieldNoiseLevelMonitoring/_FieldNoiseLevelMonitoringList');
        $('#ShiftName').val("");
    }

    function CancelNameValues() {
       // $('#ParameterMasterId').val(-1);
        $('#ShiftName').val("");
        $('#TestMethodId').val(-1);
        $('#TimeDuration').val("");
        $('#FileName').val("");
        $('#LocationGrid').val("");
        $('#DayNight').val("");
        $('#LeqFastResponse').val("");
        $('#LeqSlowResponse').val("");
        $('#NoisePara_L10').val("");
        $('#NoisePara_L50').val("");
        $('#NoisePara_L90').val("");
        $('#NoisePara_Lmin').val("");
        $('#NoisePara_Lmax').val("");
        $('#btnAdd').val("Add")
        $('#btnCancel').css('display', 'none')
        $('#SrNo').val(0)
    }
    function SetNameValues() {
        debugger;
       // $('#ParameterName').val($('#ParameterMasterId option:selected').text());
        $('#TestMethodName').val($('#TestMethodId option:selected').text());
    }

    //$('#ParameterMasterId').change(function () {
    //    debugger
    //    if ($('#ParameterMasterId').val() == '') {
    //        $('#TestMethodId').html('');
    //        $('#TestMethodId').append('<option value="">---Select---</option>');
    //    }
    //    else {

    //        $('#TestMethodId').html('');
    //        $('#TestMethodId').append('<option value="">---Select---</option>');
    //        $.ajax({
    //            url: '/FieldDetermination/GetTestMethod?EnquirySampleID=' + $('#EnquirySampleID').val() + "&ParameterMasterId=" + $('#ParameterMasterId').val(),
    //            type: 'Get',
    //            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
    //            dataType: 'json',
    //            success: function (result) {
    //                debugger
    //                $.each(result.result, function (i, item) {
    //                    $('#TestMethodId').append('<option value="' + item.TestMethodId + '">' + item.TestMethodName + '</option>');
    //                })

    //                $('#TestMethodId').append('<option value="' + 0 + '">' + "Not Required" + '</option>');
    //            },
    //            error: function (data) {
    //            }
    //        });
    //    }
    //});
</script>

Areas/FieldDetermination/Views/FieldNoiseLevelMonitoring/_FieldSourceNoiseLevelList.cshtml
@model LIMS_DEMO.Areas.FieldDetermination.Models.FDNoiseLevelMonitoringModel

@using (Ajax.BeginForm("_FieldSourceNoiseLevelList", "FieldNoiseLevelMonitoring", new { area = "FieldDetermination" }, new AjaxOptions() { HttpMethod = "Post", OnSuccess = "FDAddSource" }, new { id = "frmAddSourceNoiseLevel" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SrNo)
    @Html.HiddenFor(model => model.FieldNoiseId)
    @Html.HiddenFor(model => model.NoiseSourceParameterId)
    
    <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h4 class="m-0 font-weight-bold text-primary text-xl-center"> Enter Values for Source Noise Level :</h4>
                </div>
                <div class="card-body">
                    <div class="col-md-12">
                        <table class="table table-bordered" id="datatable" data-filter="#filter" data-filter-text-only="true" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        Shift
                                    </th>
                                    <th>
                                        Day/Night
                                    </th>
                                    <th>
                                        TestMethod
                                    </th>
                                    <th>
                                        Unit
                                    </th>
                                    <th>
                                        Location
                                    </th>
                                    <th>
                                        Time
                                    </th>
                                    <th>
                                        Inside
                                    </th>
                                    <th>
                                        Outside
                                    </th>
                                    <th>
                                        Insertion Loss
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <select class="form-control" id="ShiftName" name="ShiftName">
                                            <option value="Select Shift" disabled>Select Shift</option>
                                            <option value="1 Hour">1 Hour</option>
                                            <option value="24 Hour">24 Hour</option>
                                            <option value="Spot Noise">Spot Noise</option>
                                        </select>
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.DayNight, new { @class = "form-control ", @placeholder = "DayOrNight" })
                                    </td>
                                    <td>
                                        @Html.DropDownListFor(model => model.TestMethodId, new SelectList(ViewBag.TestMethod, "TestMethodId", "TestMethodName"), "--- Select ---", new { @class = "form-control" })
                                        @Html.HiddenFor(model => model.TestMethodName)
                                    </td>
                                    <td>
                                        @Html.DropDownListFor(model => model.UnitId, new SelectList(ViewBag.TestMethod, "UnitId", "Unit"), "--- Select ---", new { @class = "form-control" })
                                        @Html.HiddenFor(model => model.UnitName)
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.LocationGrid, new { @class = "form-control ", @placeholder = "Location" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.TimeSource, new { @class = "form-control ", @placeholder = "Time" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.Inside, new { @class = "form-control ", @placeholder = "Inside" })

                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.Outside, new { @class = "form-control ", @placeholder = "Outside" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.InsertionLoss, new { @class = "form-control ", @placeholder = "Insertion Loss" })
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-12">
                        @{ string btnText = "Add";
                            if (Model.SrNo != 0)
                            {
                                btnText = "Update";
                                <input class="btn btn-primary btn-sm alignright" onclick="CancelSourceNameValues();" id="btnCancel" value="Cancel" />
                            }
                        }
                        <input class="btn btn-success btn-sm alignright" onclick="SetSourceNameValues();" type="submit" id="btnAdd" value="@btnText" />

                    </div>
                </div>
            </div>
        </div>
  
}

<script>

    $(function () {
        $("#frmAddSourceNoiseLevel").removeData("validator");
        $("#frmAddSourceNoiseLevel").removeData("unobtrusiveValidation");
        $.validator.unobtrusive.parse("#frmAddSourceNoiseLevel");
    })

    function FDAddSource(result) {
        $('#divListSource').load('/FieldDetermination/FieldNoiseLevelMonitoring/_FDSourceLevelGridList');
        $('#divAddSourceNoiseLevel').load('/FieldDetermination/FieldNoiseLevelMonitoring/_FieldSourceNoiseLevelList');
        $('#ShiftName').val("");
    }

    function CancelSourceNameValues() {
        //$('#ParameterMasterId').val(-1);
        $('#ShiftName').val("");
        $('#TestMethodId').val(-1);
        $('#UnitId').val(-1);
        $('#TimeSource').val("");
        $('#DayNight').val("");
        $('#LocationGrid').val("");
        $('#Inside').val("");
        $('#Outside').val("");
        $('#InsertionLoss').val("");
        $('#btnAdd').val("Add")
        $('#btnCancel').css('display', 'none')
        $('#SrNo').val(0)
    }

    function SetSourceNameValues() {
        debugger;
       //$('#ParameterName').val($('#ParameterMasterId option:selected').text());
        $('#TestMethodName').val($('#TestMethodId option:selected').text());
        $('#UnitName').val($('#UnitId option:selected').text());
    }

    //$('#ParameterMasterId').change(function () {
    //    debugger
    //    if ($('#ParameterMasterId').val() == '') {
    //        $('#TestMethodId').html('');
    //        $('#TestMethodId').append('<option value="">---Select---</option>');
    //        $('#UnitId').html('');
    //        $('#UnitId').append('<option value="">---Select---</option>');
    //    }
    //    else
    //    {

    //        $('#TestMethodId').html('');
    //        $('#TestMethodId').append('<option value="">---Select---</option>');
    //        $('#UnitId').html('');
    //        $('#UnitId').append('<option value="">---Select---</option>');
    //        $.ajax({
    //            url: '/FieldDetermination/GetTestMethod?EnquirySampleID=' + $('#EnquirySampleID').val() + "&ParameterMasterId=" + $('#ParameterMasterId').val(),
    //            type: 'Get',
    //            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
    //            dataType: 'json',
    //            success: function (result) {
    //                debugger
    //                $.each(result.result, function (i, item) {
    //                    $('#TestMethodId').append('<option value="' + item.TestMethodId + '">' + item.TestMethodName + '</option>');
    //                    $('#UnitId').append('<option value="' + item.UnitId + '">' + item.Unit + '</option>');
    //                })

    //                $('#TestMethodId').append('<option value="' + 0 + '">' + "Not Required" + '</option>');
    //            },
    //              error: function (data) {
    //            }
    //        });
    //    }
    //});

</script>