Areas/Configuration/Controllers/DisciplineMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LIMS_DEMO.BAL;
using LIMS_DEMO.BAL.Configuration;
using LIMS_DEMO.Core.Configuration;
using LIMS_DEMO.Areas.Configuration.Models;
using LIMS_DEMO.Core;

namespace LIMS_DEMO.Areas.Configuration.Controllers
{
    public class DisciplineMasterController : Controller
    {
        string strStatus = "";
        public DisciplineMasterController()
        {
            BALFactory.disciplineMasterBAL = new DisciplineMasterBAL();
            //BALFactory.dropdownsBAL = new BAL.Dropdowns.DropdownsBAL();
        }
        // GET: Configuration/DisciplineMaster
        public ActionResult AddDiscipline(int? DisciplineId=0)
        {
            DisciplineMasterModel model = new DisciplineMasterModel();
            if(DisciplineId != 0)
            {
                CoreFactory.disciplineMasterEntity = BALFactory.disciplineMasterBAL.GetDetailsDiscipline((Int32)DisciplineId);
                if(CoreFactory.disciplineMasterEntity != null)
                {
                    model.DisciplineId = CoreFactory.disciplineMasterEntity.DisciplineId;
                    model.Discipline = CoreFactory.disciplineMasterEntity.Discipline;
                    model.IsActive = CoreFactory.disciplineMasterEntity.IsActive;
                }
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult DisciplineList()
        {
            CoreFactory.disciplineList = BALFactory.disciplineMasterBAL.GetDisciplineList();
            List<DisciplineMasterModel> modelList = new List<DisciplineMasterModel>();
            foreach (var Item in CoreFactory.disciplineList)
            {
                modelList.Add(new DisciplineMasterModel()
                {
                    Discipline = Item.Discipline,
                    DisciplineId = Item.DisciplineId,
                    IsActive = Item.IsActive
                });
            }
            return View(modelList);
        }
        [HttpPost]
        public ActionResult AddDiscipline(DisciplineMasterModel model)
        {
            DisciplineMasterEntity disciplineMasterEntity = new DisciplineMasterEntity();
            disciplineMasterEntity.DisciplineId = model.DisciplineId;
            disciplineMasterEntity.Discipline = model.Discipline;
            disciplineMasterEntity.EnteredBy = 1;
            disciplineMasterEntity.EnteredDate = DateTime.Now;
            disciplineMasterEntity.ModifiedDate = model.ModifiedDate;
            disciplineMasterEntity.IsActive = true;
            var result = BALFactory.disciplineMasterBAL.AddDiscipline(disciplineMasterEntity);
            //if (model.DisciplineId == 0)
            //{
            //    strStatus = BALFactory.disciplineMasterBAL.AddDiscipline(CoreFactory.disciplineMasterEntity);
            //    return Json(new { Status = strStatus, message = "Discipline has been registerd successfully." }, JsonRequestBehavior.AllowGet);
            //}
            //else
            //{
            //    strStatus = BALFactory.disciplineMasterBAL.UpdateDiscipline(CoreFactory.disciplineMasterEntity);
            //    return Json(new { Status = strStatus, message = "Discipline has been updated successfully." }, JsonRequestBehavior.AllowGet);
            //}
            if (result == "success")
            {
                return RedirectToAction("DisciplineList");
            }
            else
            {
                Response.StatusCode = (int)System.Net.HttpStatusCode.OK;
                return Json(new { status = "success", message = "Record Updated Failed." });
            }

        }
         public ActionResult DeleteDiscipline(int DisciplineId)
        {
            strStatus = BALFactory.disciplineMasterBAL.DeleteDiscipline(DisciplineId);
            if (strStatus == "success")
            {
                TempData["message"] = "Discipline has been deleted successfully.";
            }
            return  RedirectToAction("DisciplineList");
        }
    }
}

Areas/Configuration/Views/DisciplineMaster/AddDiscipline.cshtml
@model LIMS_DEMO.Areas.Configuration.Models.DisciplineMasterModel
@{
    ViewBag.Title = "AddDiscipline";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">

            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Discipline</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                @*<li class="breadcrumb-item"><a href="index.html">Configuration</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Discipline</li>
                                    <li class="breadcrumb-item active" aria-current="page">Add Discipline</li>*@
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right">
                        <div class="dropdown">
                            <a class="btn btn-primary" href="@Url.Action("DisciplineList","DisciplineMaster")" role="button">
                                Discipline List
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Default Basic Forms Start -->
            <div class="pd-20 card-box mb-30">
                <div class="clearfix">
                    <div class="pull-left">
                        <h4 class="text-blue h4">Add Discipline</h4>
                        <!--<p class="mb-30">-->@*All bootstrap element classies*@<!--</p>-->
                    </div>
                    @*<div class="pull-right">
                            <a href="#basic-form1" class="btn btn-primary btn-sm scroll-click" rel="content-y" data-toggle="collapse" role="button"><i class="fa fa-code"></i> Source Code</a>
                        </div>*@
                </div>
                <div>
                    @using (Ajax.BeginForm("AddDiscipline", "DisciplineMaster", new AjaxOptions() { HttpMethod = "Post", OnSuccess = "AddDisciplineSuccess" }))
                    {
                        @Html.ValidationSummary(true)
                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Discipline Name</label>
                            <div class="col-sm-12 col-md-10">
                                @*<input class="form-control" placeholder="Search Here" type="search">*@
                                @Html.TextBoxFor(model => model.Discipline, new { @class = "form-control", placeholdder = "Discipline Name" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-12 col-md-2 col-form-label">Is Active</label>
                            <div class="col-sm-12 col-md-10">
                                <label for="square-radio-1" class="radio-btn-pd"> @Html.RadioButtonFor(model => model.IsActive, "True", new { @checked = "checked" }) Yes </label>
                                <label for="square-radio-2" class="radio-btn-pd"> @Html.RadioButtonFor(model => model.IsActive, "False") No</label>
                            </div>
                        </div>
                        <div class="form-group row">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    }
                </div>
                <div class="collapse collapse-box" id="basic-form1">
                    <div class="code-box">
                        <div class="clearfix">

                            <a href="javascript:;" class="btn btn-primary btn-sm code-copy pull-left" data-clipboard-target="#copy-pre"><i class="fa fa-clipboard"></i> Copy Code</a>
                            <a href="#basic-form1" class="btn btn-primary btn-sm pull-right" rel="content-y" data-toggle="collapse" role="button"><i class="fa fa-eye-slash"></i> Hide Code</a>
                        </div>
                        <pre>
                        <code class="xml copy-pre" id="copy-pre"></code>
                        </pre>
                    </div>
                </div>
            </div>
            <!-- Default Basic Forms End -->
        </div>
    </div>
</div>

<script>
    function AddDisciplineSuccess(result) {
        if (result.Status == "success") {
            alert(result.message);
            location.href = '/Configuration/DisciplineList';
        }
    }
</script>

Areas/Configuration/Views/DisciplineMaster/DisciplineList.cshtml
@model IEnumerable<LIMS_DEMO.Areas.Configuration.Models.DisciplineMasterModel>
@{
    ViewBag.Title = "DisciplineList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="mobile-menu-overlay"></div>
<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Discipline List</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Configuration</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Discipline List</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right">
                        <div class="dropdown">
                            <a class="btn btn-primary" href="@Url.Action("AddDiscipline","DisciplineMaster")" role="button" >
                                Add Discipline
                            </a>

                        </div>
                    </div>
                </div>
            </div>
            <!-- Simple Datatable start -->
            <div class="card-box mb-30">
                <div class="pd-20">
                    <h4 class="text-blue h4">Discipline List</h4>
                    <p class="mb-0"> <a class="text-primary" href="https://datatables.net/" target="_blank"></a></p>
                </div>
                <div class="pb-20">
                    
                    <table class="data-table table stripe hover nowrap">
                        <thead>
                            <tr>
                                <th class="table-plus datatable-nosort">All</th>
                                <th class="table-plus datatable-nosort">Discipline</th>
                                <th class="table-plus datatable-nosort">IsActive</th>
                                <th class="datatable-nosort">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                int SerialNumber = 1;
                                foreach (var item in Model)
                                {
                                    <tr DisciplineId="@item.DisciplineId" DisciplineName="@item.Discipline">
                                        <td>@SerialNumber</td>
                                        <td>@item.Discipline</td>
                                        <td>@item.IsActive</td>
                                        <td>
                                            <div class="dropdown">
                                                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                                                    <i class="dw dw-more"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                                    @*<a class="dropdown-item" href="#"><i class="dw dw-eye"></i> View</a>*@
                                                    <a class="dropdown-item" href="@Url.Action("AddDiscipline","DisciplineMaster",new {DisciplineId=item.DisciplineId })" title="Edit" id="rowedit_@SerialNumber" operation="edit"><i class="dw dw-edit2"></i> Edit</a>
                                                    <a class="dropdown-item" href="#" onclick="Delete(@item.DisciplineId);"><i class="dw dw-delete-3"></i> Delete</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    ++SerialNumber;
                                }
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="5">
                                    <div class="pagination pagination-centered"></div>
                                </td>
                            </tr>

                        </tfoot>
                    </table>
                </div>
            </div>
            <!-- Simple Datatable End -->
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script>
    function Delete(id) {

        swal({
            title: 'Are you sure?',
            text: "You wan't to delete this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes',
            cancelButtonText: 'No',
            confirmButtonClass: 'btn btn-success margin-5',
            cancelButtonClass: 'btn btn-danger margin-5',
            buttonsStyling: false
        }).then(function () {
            debugger;
            Deleted(id);
        })
    }
    function Deleted(Id) {
        $.ajax({
            url: '/DisciplineMaster/DeleteDiscipline',
            type: 'Get',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            dataType: 'json',
            data: { DisciplineId: Id },
            success: function (result) {
                debugger;
                swal(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
                var x = '/DisciplineMaster/DisciplineList'
                window.location = x;
            },
            error: function (data) {
            }
        });
    }
</script>